### ISSUE TITLE
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'create' of undefined

### ISSUE THREAD

**Issue by liuchuancong** [EddyVerbruggen/nativescript-feedback#24]
: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'create' of undefined
JS: TypeError: Cannot read property 'create' of undefined
JS:     at Promise (file:///data/data/com.ibenchu.muslim/files/app/tns_modules/nativescript-feedback/feedback.js:17:55)
JS:     at new ZoneAwarePromise (file:///data/data/com.ibenchu.muslim/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:777:29)
JS:     at Feedback.show (file:///data/data/com.ibenchu.muslim/files/app/tns_modules/nativescript-feedback/feedback.js:15:16)
JS:     at file:///data/data/com.ibenchu.muslim/files/app/register/register.component.js:69:28
JS:     at ZoneDelegate.invoke (file:///data/data/com.ibenchu.muslim/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:365:26)
JS:     at Object.onInvoke (file:///data/data/com.ibenchu.muslim/files/app/tns_modules/@angular/core/bundles/core.umd.js:4798:33)
JS:     at ZoneDelegate.invoke (file:///data/data/com.ibenchu.muslim/files/app/tns_modules/nativescript-angular/zone-js/dist/zon...

**Comment by liuchuancong** [comment]
i find  'create'  but i don't konw how handle this error

**Comment by liuchuancong** [comment]
i remove the platforms folder and build again
