### ISSUE TITLE
Vue-demo doesn't work

### ISSUE THREAD

**Issue by DepickereSven** [EddyVerbruggen/nativescript-feedback#53]
I used the following commands:
```
git clone https://github.com/EddyVerbruggen/nativescript-feedback
cd nativescript-feedback/src
npm run demo-vue.android
```
Then I got this error:
```
The current application is not compatible with NativeScript CLI 6.0.
Use the `tns migrate` command to migrate the app dependencies to a form compatible with NativeScript 6.0.
Running this command will not affect the codebase of the application and you might need to do additional changes manually – for more information, refer to the instructions in the following blog post: https://www.nativescript.org/blog/nativescript-6.0-application-migration
```

So I tried to update it to Nativescript 6.0

By the following commands:

```
cd ..
cd demo-vue
tns migrate
cd ..
cd src/
npm run demo-vue.android
```

Error log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\svend\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'demo-vue.android' ]
2 info using npm@6.4.1
3 info using node@v10.13.0
4 verbose run-script [ 'predemo-vue.android',
4 verbose run-script   'demo-vue.android',
4 verbose run-script   'postdemo-vue.android' ]
5 info lifecycle nativescript-feedback@1.3.10~predemo-vue.android: nativescript-feedback@1.3.10
6 info lifecycle nativescript-feedback@1.3.10~demo-vue.android: nativescript-feedback@1.3.10
7 verbose lifecycle nativescript-feedback@1.3.10~demo-vue.android: unsafe-perm in lifecycle true
8 verbose lifecycle nativescript-feedback@1.3.10~demo-vue.android: PATH: C:\Users\svend\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;F:\Dev\TRA\Test\nativescript-feedback\src\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\HP\HP Performance Advisor;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\dotnet\;F:\Go\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files\Git\cmd;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Java\jdk1.8.0_191\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\wamp64\bin\php\php7.3.8;C:\ProgramData\ComposerSetup\bin;C:\Users\svend\.cargo\bin;C:\Users\svend\AppData\Local\Microsoft\WindowsApps;C:\Users\svend\AppData\Local\GitHubDesktop\bin;C:\Users\svend\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\Microsoft VS Code\bin;F:\Program Files\SQL Operations Studio\bin;C:\Exercism;C:\Users\svend\AppData\Roaming\npm;C:\Users\svend\AppData\Local\Yarn\bin;C:\Users\svend\AppData\Roaming\Composer\vendor\bin
9 verbose lifecycle nativescript-feedback@1.3.10~demo-vue.android: CWD: F:\Dev\TRA\Test\nativescript-feedback\src
10 silly lifecycle nativescript-feedback@1.3.10~demo-vue.android: Args: [ '/d /s /c',
10 silly lifecycle   'npm run build && cd ../demo-vue && tns run android --bundle' ]
11 info lifecycle nativescript-feedback@1.3.10~demo-vue.android: Failed to exec demo-vue.android script
12 verbose stack Error: nativescript-feedback@1.3.10 demo-vue.android: `npm run build && cd ../demo-vue && tns run android --bundle`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (C:\Users\svend\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:182:13)
12 verbose stack     at maybeClose (internal/child_process.js:962:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
13 verbose pkgid nativescript-feedback@1.3.10
14 verbose cwd F:\Dev\TRA\Test\nativescript-feedback\src
15 verbose Windows_NT 10.0.18362
16 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\svend\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "demo-vue.android"
17 verbose node v10.13.0
18 verbose npm  v6.4.1
19 error file C:\WINDOWS\system32\cmd.exe
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error nativescript-feedback@1.3.10 demo-vue.android: `npm run build && cd ../demo-vue && tns run android --bundle`
23 error spawn ENOENT
24 error Failed at the nativescript-feedback@1.3.10 demo-vue.android script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by EddyVerbruggen** [comment]
Thanks, I've just updated the Vue demo to N6 myself and all works fine. Remove your project, and run

```
git clone https://github.com/EddyVerbruggen/nativescript-feedback
cd nativescript-feedback/src
npm run demo-vue.android
```

**Comment by DepickereSven** [comment]
I did what you asked and I still don't work. 
I got the following error;

```
F:\Dev\TRA\Test\nativescript-feedback\demo-vue\node_modules\webpack-cli\bin\cli.js:93
                                throw err;
                                ^

Error: The entry module main specified in F:\Dev\TRA\Test\nativescript-feedback\demo-vue\app/package.json doesn't exist!    at Object.exports.getEntryModule (F:\Dev\TRA\Test\nativescript-feedback\demo-vue\node_modules\nativescript-dev-webpack\index.js:43:15)
    at module.exports.env (F:\Dev\TRA\Test\nativescript-feedback\demo-vue\webpack.config.js:61:35)
    at handleFunction (F:\Dev\TRA\Test\nativescript-feedback\demo-vue\node_modules\webpack-cli\bin\utils\prepareOptions.js:21:13)
    at prepareOptions (F:\Dev\TRA\Test\nativescript-feedback\demo-vue\node_modules\webpack-cli\bin\utils\prepareOptions.js:9:5)
    at requireConfig (F:\Dev\TRA\Test\nativescript-feedback\demo-vue\node_modules\webpack-cli\bin\utils\convert-argv.js:119:14)
    at F:\Dev\TRA\Test\nativescript-feedback\demo-vue\node_modules\webpack-cli\bin\utils\convert-argv.js:125:17
    at Array.forEach (<anonymous>)
    at module.exports (F:\Dev\TRA\Test\nativescript-feedback\demo-vue\node_modules\webpack-cli\bin\utils\convert-argv.js:123:15)
    at yargs.parse (F:\Dev\TRA\Test\nativescript-feedback\demo-vue\node_modules\webpack-cli\bin\cli.js:71:45)
    at Object.parse (F:\Dev\TRA\Test\nativescript-feedback\demo-vue\node_modules\webpack-cli\node_modules\yargs\yargs.js:567:18)
    at F:\Dev\TRA\Test\nativescript-feedback\demo-vue\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (F:\Dev\TRA\Test\nativescript-feedback\demo-vue\node_modules\webpack-cli\bin\cli.js:365:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (F:\Dev\TRA\Test\nativescript-feedback\demo-vue\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
Executing webpack failed with exit code 1.

```

**Comment by EddyVerbruggen** [comment]
I don't know what's up with your setup then, but let's not waste too much time on this. Just copy what you need from the demo.
