### ISSUE TITLE
Error: android.view.InflateException using nativescript plugin-feedback

### ISSUE THREAD

**Issue by ittrad-mobile-lab** [EddyVerbruggen/nativescript-feedback#61]
Someone knows why this error only on android?
IOS is working like a charm.

```
firebase.update(`/puzzle/${puzzleItem.idUser}/${currentItemKey}`, puzzleItem).then(
        (resultUpdate) => {
                this._ngZone.run(() => {
                // FEEDBACK ERROR ??!!!
                this.feedback.show({
                    message: "Easiest thing ever, right?"
                });

                this.refreshPuzzle(listIndexItemsClicked);
            });
    }
);

JS: ERROR Error: Uncaught (in promise): Error: android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class <unknown>
JS: (file:///node_modules/nativescript-feedback/feedback.js:17:0)
JS:     at ZoneAwarePromise(file:///node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:902:0)
JS:     at show(file:///node_modules/nativescript-feedback/feedback.js:15:0)
JS:     at (file:///src/app/puzzle/puzzle.component.ts:384:50)
JS:     at push.../node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js.ZoneDelegate.invoke(file:///node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:388:0)
JS:     at onInvoke(file:///node_modules/@angular/core/fesm5/core.js:26256:0)
JS:     at push.../node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js.ZoneDelegate.invoke(file:///node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:387:0)
JS:     at push.../node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js.Zone.run(file:...
```

**Comment by arjes** [comment]
I ran into this when I tried to open a feedback over top of https://github.com/EddyVerbruggen/nativescript-barcodescanner
